name: CI

on:
  push:
  pull_request:

jobs:
  quality:
    name: Code Quality & Automated Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Linter
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Linter (Ruff)
        run: ruff check .

      # NOUVEAU : Création d'un fichier .env vide pour Docker Compose
      - name: Create dummy .env file for Docker
        run: touch .env

      - name: Run Django Tests in Docker Compose
        run: docker compose run --rm web python manage.py test

      - name: Clean up Docker resources
        if: always()
        run: docker compose down -v --remove-orphans